#+HTML_HEAD:<link href="https://free.bboxtype.com/embedfonts/?family=FiraSans:400" rel="stylesheet"> <style>        body { max-width: 75ch; padding: 2rem; margin: auto; font-family: 'Fira Sans', sans-serif;} a {color: grey;} </style>
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [letterpaper,10pt]
#+LATEX_HEADER: \usepackage{lmodern}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: html-postamble:nil html-scripts:nil author:nil  html-preamble:nil toc:nil num:nil broken-links:t  html-style:nil


#+TITLE: Michael Tu, PhD

* Experience

#+HTML: <center>
| Title                    | Institution                          | Year           |
|--------------------------+--------------------------------------+----------------|
| Chief Scientific Officer | Liquid Diagnostics LLC               | 2020 - Present |
| Co-Investigator          | NIH NCI U01: EFIRM Liquid Biopsy     | 2018 - Present |
| Director of R&D          | EZLife Bio Inc                       | 2017 - 2019    |
| T90 NIH Trainee          | UCLA School of Dentistry             | 2015 - 2017    |
| T32 NIH Trainee          | UCLA School of Dentistry             | 2012 - 2015    |
| Graduate Researcher      | UCLA Dept. of Electrical Engineering | 2010 - 2012    |
| Consultant               | Evidia Biosciences                   | 2011           |
| Teacher's Assistant      | UCLA Dept. of Chemistry              | 2011           |
| Teacher's Assistant      | UCLA School of Engineering           | 2009 - 2013    |
#+HTML: </center>


* Education

#+HTML: <center>
| Institution | Degree                       | Year |
|-------------+------------------------------+------|
| UCLA        | PhD - Biomedical Engineering | 2015 |
| UCLA        | MS - Biomedical Engineering  | 2010 |
| UCLA        | BS - Bioengineering          | 2009 |
#+HTML: </center>


* Select Publications
- M. K. Tu, et al. “The Kinetics of COVID-19 Vaccine Response in a Community-Vaccinated Population,” J.I., p. ji2100919, Jan. 2022, doi: 10.4049/jimmunol.2100919.
- S. H. Chiang, M.Tu, et al., “Development and validation of a quantitative, non-invasive, highly sensitive and specific, electrochemical assay for anti-SARS-CoV-2 IgG antibodies in saliva,” PLoS ONE, vol. 16, no. 7, p. e0251342, Jul. 2021, doi: 10.1371/journal.pone.0251342.
- M. Tu et al., “Rapid PCR-Free Meat Species Identification using Electric Field Induced Release and Measurement (EFIRM®),” Analytica Chimica Acta, p. S000326701931414X, Nov. 2019, doi: 10.1016/j.aca.2019.11.051.
- M. Tu et al., “Electric Field Induced Release and Measurement (EFIRM): Characterization and Technical Validation of a Novel Liquid Biopsy Platform in Plasma and Saliva,” The Journal of Molecular Diagnostics, p. S1525157820303500, Jun. 2020, doi: 10.1016/j.jmoldx.2020.05.005.
- M. Tu, D. Chia, F. Wei, and D. Wong, “Liquid biopsy for detection of actionable oncogenic mutations in human cancers and electric field induced release and measurement liquid biopsy (eLB),” The Analyst, 2016, doi: 10.1039/C5AN01863C.
- M. Suh et al., “A Remote Patient Monitoring System for Congestive Heart Failure,” Journal of Medical Systems, vol. 35, no. 5, pp. 1165–1179, May 2011, doi: 10.1007/s10916-011-9733-y.
- [[https://orcid.org/0000-0002-7227-4030][Full list📃]]


